import React, { useEffect, useState } from 'react';
import Button from '@mui/material/Button';
import Container from '@mui/material/Container';
import { Backdrop, Box, CircularProgress } from '@mui/material';
import Head from 'next/head'
import Image from 'next/image'
import homeStyles from '../styles/Home.module.css'
import styles from '../styles/Game.module.css'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faLocationDot } from '@fortawesome/free-solid-svg-icons';
import geohash from 'ngeohash';
import { CheckIn } from 'zk-schnitzelhunt';

// let CheckIn; // this will hold the dynamically imported './sudoku-zkapp.ts'

function MyApp() {

  const [lat, setLat] = useState(null);
  const [lng, setLng] = useState(null);
  const [geoHash, setGeoHash] = useState();
  const [geoHashInt, setGeoHashInt] = useState();
  let [zkapp, setZkapp] = useState();
  let [isLoading, setLoading] = useState(false);
  let [isFirstRender, setFirstRender] = useState(true);
  let [showSubmissionSuccess, setSubmissionSuccess] = useState(false);
  let [showSubmissionError, setSubmissionError] = useState(false);

  useEffect(() => {
    console.log('useEffect ran');

    async function deploy() {
      console.log('firstRender '+isFirstRender);
      if (!isFirstRender || isLoading) return;
      setFirstRender(false);
      setLoading(true);
      const {CheckIn} = await import('../../contracts/build/src/CheckIn.js');
      let zkapp = await CheckIn.deployApp();
      setZkapp(zkapp);
      setLoading(false);
      console.log('Initial state checkedIn '+zkapp.getState().checkedIn);
      console.log('Initial state targetGeoHash '+zkapp.getState().targetGeoHash);
      console.log(zkapp);
    }
    deploy();
    
  }, []);

  function shareLocation() {
    if (showSubmissionError) {
      setSubmissionError(false);
    }
    navigator.geolocation.getCurrentPosition((position) => {
      console.log('Latitude is :', position.coords.latitude);
      console.log('Longitude is :', position.coords.longitude);
      setLat(position.coords.latitude);
      setLng(position.coords.longitude);
      setGeoHashInt(
        geohash.encode_int(
          position.coords.latitude,
          position.coords.longitude,
        )
      );

      // bounding box ankeruhr
      let bboxes_int = geohash.bboxes_int(48.210766,16.373587,48.2107804, 16.3737335);
      console.log(bboxes_int);
      console.log('bla '+bboxes_int);

      let coord1 = geohash.decode_int(3669811487352851);
      console.log('coord1 lat '+coord1.latitude+ ' long '+coord1.longitude);
      let coord2 = geohash.decode_int(3669811487352981);
      console.log('coord2 lat '+coord2.latitude+ ' long '+coord2.longitude);
      let coord3 = geohash.decode_int(3669811487353538);
      console.log('coord3 lat '+coord3.latitude+' long '+ coord3.longitude);
      
    });
  };

  const submit = async (zkapp) => {
    console.log('Submitting location: '+lat+','+lng);
    setLoading(true);
    // uncomment line below to test happy path
    const {CheckIn} = await import('../../contracts/build/src/CheckIn.js');
    let location = new CheckIn.LocationCheck(48.208487, 16.372571);
    // let location = new CheckIn.LocationCheck(lat, lng);
    console.log(CheckIn);
    await zkapp.checkIn(location);
    let checkin = zkapp?.getState().checkedIn;
    if (checkin) {
      setSubmissionSuccess(true);
    } else {
      setSubmissionError(true);
    }
    setLat(null);
    setLng(null);
    setLoading(false);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>zk schnitzeljagd</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <main>  

    <div>
      <Backdrop
        sx={{ color: '#fff', zIndex: (theme) => theme.zIndex.drawer + 1 }}
        open={isLoading || isFirstRender}
      >
        <CircularProgress color="inherit" />
      </Backdrop>
    </div>
    <div>
        <Container fixed>
          <Box className={styles.riddleBox}
          >
            <p className={styles.riddle}>Some question on sharing location ... </p>
          </Box>
          <Box className={styles.locationBox}
          >
            <p className={styles.location}>
              Solve by sharing your location 👉 <FontAwesomeIcon icon={faLocationDot} onClick={shareLocation} style={{color: '#ffafbd'}} size="2x" />
            </p>
          </Box>
          {!showSubmissionError && !showSubmissionSuccess && <Box
            className={styles.location}
          >
            <p>
              {lat && <p>Latitude: {lat}, </p>}
              {lng && <p>Longitude: {lng}</p>}
            </p>
            <p style={{ marginLeft: '20px', marginTop: '10px' }}>
              {lat && lng && (
                <Button
                  variant="contained"
                  onClick={()=>{
                    submit(zkapp);
                  }}
                  style={{ backgroundColor: '#ffafbd' }}
                >
                  Submit solution
                </Button>
              )}
            </p>
          </Box>}

          {showSubmissionError && <Box className={styles.locationBox}>
            <p className={styles.submissionError}>
              Wrong Location, try again!
            </p>
      </Box>}

      {showSubmissionSuccess && <Box className={styles.locationBox}>
            <p className={styles.submissionError}>
              Nice one! 
            </p>
      </Box>}

        </Container>
      </div>
      </main>

      <footer className={homeStyles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={homeStyles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default MyApp;