import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useEffect } from "react";
import { isReady, PublicKey } from "snarkyjs";
import styles from "../styles/Home.module.css";

export default function Home() {
  useEffect(() => {
    (async () => {
      await isReady;
      // const { Add } = await import('../../contracts/build/src/Schnitzel.js');

      // // Update this to use the address (public key) for your zkApp account
      // // To try it out, you can try this address for an example "Add" smart contract that we've deployed to
      // // Berkeley Testnet B62qqkb7hD1We6gEfrcqosKt9C398VLp1WXeTo1i9boPoqF7B1LxHg4
      // const zkAppAddress = '';
      // // This should be removed once the zkAppAddress is updated.
      // if (!zkAppAddress) {
      //   console.error(
      //     'The following error is caused because the zkAppAddress has an empty string as the public key. Update the zkAppAddress with the public key for your zkApp account, or try this address for an example "Add" smart contract that we deployed to Berkeley Testnet: B62qqkb7hD1We6gEfrcqosKt9C398VLp1WXeTo1i9boPoqF7B1LxHg4'
      //   );
      // }

      // const zkAppInstance = new Add(PublicKey.fromBase58(zkAppAddress));
    })();
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>zk schnitzelhunt</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>zk schnitzelhunt</h1>

        <p className={styles.description}>
          <Link href="/game">
            <button>START NEW GAME</button>
          </Link>
        </p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
