#
# ci.yml
#
# Run tests for all pushed commits and opened pull requests on Github.
#

name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Set up NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Git checkout
        uses: actions/checkout@v2
      - name: NPM ci, build, & test
        working-directory: ./contracts
        run: |
          npm ci
          npm run build --if-present
          npm test
      - name: Install Playwright
        working-directory: ./ui
        run: | 
          npm ci
          npx playwright install --with-deps chromium
      - name: Run E2E Tests
        working-directory: ./ui
        run: | 
          npm run test:e2e
        env:
          CI: true
      - name: Upload E2E Test Artifacts
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: e2e-tests-report
          path: tests/report/
          retention-days: 10